# generated by datamodel-codegen:
#   filename:  bundled.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class SchemaVersion(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9]+\\.[0-9]+$")]


class Scope(Enum):
    shared = "shared"
    per_team = "per_team"


class IdOffset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vmid: Annotated[int | None, Field(ge=0)] = None
    ip: Annotated[int | None, Field(ge=0)] = None


class Replication(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope: Scope
    id_offset: IdOffset | None = None


class Kind(Enum):
    catalog_role = "catalog_role"
    catalog_container = "catalog_container"
    inline_yaml = "inline_yaml"
    file_upload = "file_upload"
    external_git = "external_git"


class AttachmentSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    ref: str | None = None
    sha: str | None = None
    url: AnyUrl | None = None
    content_ref: str | None = None


class Scope1(Enum):
    node = "node"
    group_inherited = "group_inherited"


class AnsiblePrimitive(Enum):
    task = "task"
    handler = "handler"
    block = "block"


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    source: AttachmentSource
    title: str | None = None
    stage: str
    order_in_stage: Annotated[int | None, Field(ge=0)] = None
    scope: Scope1 | None = None
    vars: dict[str, Any] | None = None
    ansible_primitive: AnsiblePrimitive | None = None
    handler_namespace: str | None = None
    target_node: str | None = None


class EnvVar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_]*$")]
    scope: Scope | None = None
    secret: bool | None = False
    required: bool | None = False
    default: Any | None = None


class Flag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    scope: Scope
    value_template: str | None = None
    points: Annotated[int | None, Field(ge=0)] = None


class NetworkAttachment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    node_ref: str
    ip: str | None = None
    ip_template: str | None = None
    dhcp: bool | None = None


class Kind1(Enum):
    vm = "vm"
    lxc = "lxc"
    docker = "docker"
    network = "network"
    router = "router"
    firewall = "firewall"
    skin = "skin"
    group = "group"


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    kind: Kind1
    replication: Replication | None = None
    host_ref: str | None = None
    config: dict[str, Any] | None = None
    networks: list[NetworkAttachment] | None = None
    attachments: list[Attachment] | None = None
    children: list[Node] | None = None


class Execution(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stages: list[str] | None = None


class Kind2(Enum):
    lab = "lab"
    gamenet = "gamenet"
    component = "component"


class CatalogEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    kind: Kind2
    name: str
    description: str | None = None
    author: str | None = None
    tags: list[str] | None = None
    nodes: list[Node] | None = None
    env: list[EnvVar] | None = None
    flags: list[Flag] | None = None
    defaults: dict[str, Any] | None = None
    execution: Execution | None = None


class NodesPatchedItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    patch: dict[str, Any]


class ProjectOverlay(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: SchemaVersion
    source_url: AnyUrl
    source_sha: str
    source_entry: str | None = None
    param_overrides: dict[str, Any] | None = None
    nodes_added: list[Node] | None = None
    nodes_removed: list[str] | None = None
    nodes_patched: list[NodesPatchedItem] | None = None
    attachments_added: list[Attachment] | None = None
    execution_override: Execution | None = None


class State(Enum):
    pending = "pending"
    deploying = "deploying"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    cancelled = "cancelled"
    unknown = "unknown"


class SubReason(Enum):
    host_unreachable = "host_unreachable"
    task_timeout = "task_timeout"
    preflight_block = "preflight_block"
    vault_rekey_blocked = "vault_rekey_blocked"
    auth_failed = "auth_failed"
    resource_overcommit = "resource_overcommit"
    image_pull_failed = "image_pull_failed"
    protected_vmid_collision = "protected_vmid_collision"


class Attempt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    scope: str
    team_id: Annotated[int | None, Field(ge=0)] = None
    state: State
    sub_reason: SubReason | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    rc: int | None = None
    event_cursor_tip: Annotated[int | None, Field(ge=0)] = None


class State1(Enum):
    pending = "pending"
    preflight_running = "preflight_running"
    preflight_review = "preflight_review"
    deploying = "deploying"
    succeeded = "succeeded"
    partial = "partial"
    failed = "failed"
    cancelled = "cancelled"
    unknown = "unknown"


class DeploymentRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    codename: str
    scenario_label: str | None = None
    project_id: str
    target_host_id: str
    catalog_sha: str | None = None
    project_sha: str | None = None
    effective_doc_hash: str | None = None
    team_count: Annotated[int, Field(ge=1)]
    state: State1
    current_attempt_id: str | None = None
    workspace_path: str
    created_at: datetime | None = None
    attempts: list[Attempt] | None = None


class EventType(Enum):
    state_transition = "state_transition"
    phase_transition = "phase_transition"
    task_start = "task_start"
    task_end = "task_end"
    host_unreachable = "host_unreachable"
    log_line = "log_line"
    redaction = "redaction"
    heartbeat = "heartbeat"
    attempt_start = "attempt_start"
    attempt_end = "attempt_end"
    proxmox_task = "proxmox_task"
    preflight_check = "preflight_check"


class EventLogEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_seq: Annotated[int, Field(ge=0)]
    attempt_id: str
    deployment_id: str | None = None
    ts: datetime
    deployer_ts: datetime | None = None
    proxmox_ts: datetime | None = None
    stage: str | None = None
    substate: str | None = None
    team_id: Annotated[int | None, Field(ge=0)] = None
    node_id: str | None = None
    event_type: EventType
    payload: dict[str, Any] | None = None


class Result(Enum):
    pass_ = "pass"
    warn = "warn"
    block = "block"


class PreflightCheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    check: str
    result: Result
    detail: str | None = None
    field_path: str | None = None


class PreflightRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deployment_id: str
    attempt_id: str
    ts: datetime
    checks: list[PreflightCheck]
    result: Result


class Status(Enum):
    ok = "ok"
    degraded = "degraded"
    unreachable = "unreachable"


class ProxmoxHostHealth(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status
    rtt_ms: Annotated[int | None, Field(ge=0)] = None
    sdn_available: bool | None = None
    at: datetime


class Kind3(Enum):
    api_token = "api_token"


class Auth(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind3
    token_id_ref: str


class ProtectedVmidsOverrideItemItem(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class ProtectedVmidsOverrideItem(RootModel[list[ProtectedVmidsOverrideItemItem]]):
    root: Annotated[
        list[ProtectedVmidsOverrideItemItem], Field(max_length=2, min_length=2)
    ]


class ProxmoxHost(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    name: str
    api_url: AnyUrl
    node_name: str
    auth: Auth
    token_scope: str | None = None
    default_bridge: str | None = None
    protected_vmids_override: list[ProtectedVmidsOverrideItem] | None = None
    added_at: datetime | None = None
    last_health_check: ProxmoxHostHealth | None = None


class Range42ScenarioSchemaV1(
    RootModel[
        CatalogEntry
        | ProjectOverlay
        | DeploymentRecord
        | EventLogEntry
        | PreflightRecord
        | ProxmoxHost
    ]
):
    root: Annotated[
        CatalogEntry
        | ProjectOverlay
        | DeploymentRecord
        | EventLogEntry
        | PreflightRecord
        | ProxmoxHost,
        Field(
            description="Canonical schema for catalog entries, project overlays, deployment records, event logs, preflight records, proxmox hosts, attachments, replication, env, and flags.",
            title="Range42 Scenario Schema v1",
        ),
    ]


Node.model_rebuild()
