"""v1 initial

Revision ID: 0001_v1_initial
Revises: 
Create Date: 2026-04-15 14:33:25.507926
"""
from alembic import op
import sqlalchemy as sa

revision = '0001_v1_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxmox_hosts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('api_url', sa.String(length=512), nullable=False),
    sa.Column('node_name', sa.String(length=128), nullable=False),
    sa.Column('token_ref', sa.String(length=128), nullable=False),
    sa.Column('token_scope', sa.String(length=256), nullable=True),
    sa.Column('default_bridge', sa.String(length=32), nullable=False),
    sa.Column('protected_vmids_override_json', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_health_check_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('auth_kind', sa.String(length=16), nullable=False),
    sa.Column('token_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('branch_strategy', sa.String(length=32), nullable=False),
    sa.Column('repo_owner', sa.String(length=128), nullable=True),
    sa.Column('repo_name', sa.String(length=128), nullable=True),
    sa.Column('subdir', sa.String(length=256), nullable=True),
    sa.Column('base_catalog_url', sa.String(length=512), nullable=True),
    sa.Column('base_catalog_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_repos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('manifest_path', sa.String(length=256), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'owner', 'repo', name='uq_source_repo')
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('codename', sa.String(length=64), nullable=False),
    sa.Column('scenario_label', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('target_host_id', sa.String(length=64), nullable=False),
    sa.Column('catalog_sha', sa.String(length=64), nullable=True),
    sa.Column('project_sha', sa.String(length=64), nullable=True),
    sa.Column('effective_doc_hash', sa.String(length=80), nullable=True),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_attempt_id', sa.String(length=64), nullable=True),
    sa.Column('workspace_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_host_id'], ['proxmox_hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename', 'scenario_label', name='uq_deployment_workspace')
    )
    op.create_table('attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('sub_reason', sa.String(length=64), nullable=True),
    sa.Column('rc', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_cursor_tip', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('artifact_dir', sa.String(length=512), nullable=True),
    sa.Column('vault_hash', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_locks',
    sa.Column('deployment_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_interval_s', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_table('preflight_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('checks_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=64), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('preflight_records')
    op.drop_table('workspace_locks')
    op.drop_table('attempts')
    op.drop_table('deployments')
    op.drop_table('source_repos')
    op.drop_table('projects')
    op.drop_table('sources')
    op.drop_table('proxmox_hosts')
    # ### end Alembic commands ###
