---
all:
  vars:
    r42_demo_output_dir: "{{ r42_workspace_dir | default('/tmp/range42-content-demo', true) }}/demo-output"
  hosts:
    content_demo:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
